# Generated by Django 2.2.11 on 2020-03-10 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theme', models.CharField(choices=[('Music', 'Music'), ('Gaming', 'Gaming'), ('Vlog', 'Vlog'), ('Review', 'Review'), ('Tutorial', 'Tutorial'), ('Educational', 'Educational'), ('For kids', 'For kids')], max_length=200)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('thumbs_down', models.IntegerField(default=0)),
            ],
        ),
    ]
